# Generated by Django 5.1.4 on 2024-12-30 10:41

import django.db.models.deletion
import django_ckeditor_5.fields
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxz123456789', editable=False, length=22, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('BIO', django_ckeditor_5.fields.CKEditor5Field()),
                ('information', models.CharField(choices=[('MIDDLE', 'Middle'), ('HIGH', 'High'), ('NO', 'No')], max_length=200)),
            ],
            options={
                'ordering': ['-uuid'],
            },
        ),
        migrations.CreateModel(
            name='Governor_District',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxz123456789', editable=False, length=22, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('information', models.CharField(choices=[('MIDDLE', 'Middle'), ('HIGH', 'High'), ('NO', 'No')], max_length=200)),
                ('BIO', django_ckeditor_5.fields.CKEditor5Field()),
            ],
            options={
                'ordering': ['-uuid'],
            },
        ),
        migrations.CreateModel(
            name='Governor_Region',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxz123456789', editable=False, length=22, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('information', models.CharField(choices=[('MIDDLE', 'Middle'), ('HIGH', 'High'), ('NO', 'No')], max_length=200)),
                ('BIO', django_ckeditor_5.fields.CKEditor5Field()),
            ],
            options={
                'ordering': ['-uuid'],
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxz123456789', editable=False, length=22, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('house_boss', models.CharField(max_length=200)),
                ('house_number', models.PositiveIntegerField()),
                ('a_b', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=200)),
                ('status', models.CharField(choices=[('POORER', 'POORER'), ('MIDDLE', 'MIDDLE'), ('RICH', 'RICH')], max_length=200)),
                ('people', models.PositiveIntegerField(blank=True)),
                ('area_kv_m', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'ordering': ['house_number', 'a_b'],
            },
        ),
        migrations.CreateModel(
            name='President',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxz123456789', editable=False, length=22, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('information', models.CharField(choices=[('MIDDLE', 'Middle'), ('HIGH', 'High'), ('NO', 'No')], max_length=200)),
                ('party', models.CharField(max_length=200)),
                ('BIO', django_ckeditor_5.fields.CKEditor5Field()),
            ],
            options={
                'ordering': ['-uuid'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxz123456789', editable=False, length=22, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('about', django_ckeditor_5.fields.CKEditor5Field()),
                ('area_km_kv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MFYs', models.PositiveIntegerField()),
                ('people', models.PositiveIntegerField()),
                ('governor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district', to='main.governor_district')),
            ],
            options={
                'ordering': ['-uuid'],
            },
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxz123456789', editable=False, length=22, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('BIO', django_ckeditor_5.fields.CKEditor5Field()),
                ('status', models.CharField(choices=[('Kindergarten', 'Kindergarten'), ('Schoolboy', 'Schoolboy'), ('Student', 'Student'), ('Worker', 'Worker')], max_length=200)),
                ('information', models.CharField(choices=[('MIDDLE', 'Middle'), ('HIGH', 'High'), ('NO', 'No')], default='NO', max_length=200)),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='human', to='main.house')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uuid'],
            },
        ),
        migrations.CreateModel(
            name='MFY',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxz123456789', editable=False, length=22, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('area_km_kv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('neighborhoods', models.PositiveIntegerField()),
                ('people', models.PositiveIntegerField()),
                ('chairman', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='C_MFY', to='main.chairman')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_MFY', to='main.district')),
            ],
            options={
                'ordering': ['-uuid'],
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxz123456789', editable=False, length=22, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('elder', models.CharField(max_length=250)),
                ('area_km_kv', models.DecimalField(decimal_places=2, max_digits=15)),
                ('houses', models.PositiveIntegerField()),
                ('people', models.PositiveIntegerField()),
                ('MFY', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mfy')),
            ],
            options={
                'ordering': ['-uuid'],
            },
        ),
        migrations.AddField(
            model_name='house',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house', to='main.neighborhood'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxz123456789', editable=False, length=22, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('bio', models.TextField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxz123456789', editable=False, length=22, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('about', django_ckeditor_5.fields.CKEditor5Field()),
                ('area_km_kv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('districts', models.PositiveIntegerField()),
                ('people', models.PositiveIntegerField()),
                ('governor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region', to='main.governor_region')),
            ],
            options={
                'ordering': ['-uuid'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district', to='main.region'),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxz123456789', editable=False, length=22, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('about', django_ckeditor_5.fields.CKEditor5Field()),
                ('flag', models.ImageField(blank=True, upload_to='images')),
                ('anthem', models.TextField()),
                ('emblem', models.ImageField(blank=True, upload_to='images')),
                ('area_km_kv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regions', models.PositiveIntegerField()),
                ('people', models.PositiveIntegerField()),
                ('president', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state', to='main.president')),
            ],
            options={
                'ordering': ['-uuid'],
            },
        ),
        migrations.AddField(
            model_name='region',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region', to='main.state'),
        ),
    ]
