# Generated by Django 5.1.4 on 2025-01-01 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governordistrict',
            name='region',
        ),
        migrations.RemoveField(
            model_name='governorregion',
            name='state',
        ),
    ]
