# Generated by Django 5.1.4 on 2025-01-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_governordistrict_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='MFYs',
            field=models.PositiveIntegerField(default=45),
        ),
    ]
