# Generated by Django 5.1.4 on 2024-12-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_chairman_uuid_alter_district_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='name',
            field=models.CharField(help_text='Masalan: Jhon Doe', max_length=200, verbose_name='Ism Kiriting'),
        ),
    ]
