# Generated by Django 5.1.4 on 2024-12-28 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_human_house_alter_human_information_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='MFY',
            new_name='MFYs',
        ),
    ]
